import { StatBlock } from './stats.js';

export type PowerTier = 1 | 2 | 3 | 4 | 5;

export type AnonymousInterceptorKind = 'PIRATE' | 'PATROL' | 'RIM_PIRATE' | 'BRIGAND' | 'REPTILOID';

export interface AnonymousInterceptorProfile {
  id: string;
  kind: AnonymousInterceptorKind;
  rosterIndex: number;
  name: string;
  shipName: string;
  shipClass: string;
  homeSystem: string;
  stats: StatBlock;
  tier: PowerTier;
}

export interface NpcProfile {
  id: string;
  name: string;
  shipName: string;
  stats: StatBlock;
  ideal: string;
  bond: string;
  flaw: string;
  /** Resist the flaw on d20 >= flawDc (disciplined = low, volatile = high). */
  flawDc: number;
  /** Power tier: 1 = mudlark, 5 = legend (PRD §6). */
  tier: PowerTier;
}

export const NPC_PROFILES: NpcProfile[] = [
  // The Original 20
  {
    id: 'npc-iron-vex',
    name: 'Iron Vex',
    shipName: 'Hammerfall',
    stats: { PILOT: 2, GUNS: 4, TRADE: 0, GRIT: 3, GUILE: 0 },
    ideal: 'Dominance',
    bond: 'Loyal to the Warlord Confed',
    flaw: 'Bloodthirsty',
    flawDc: 14,
    tier: 3,
  },
  {
    id: 'npc-silk-dagger',
    name: 'Silk Dagger',
    shipName: 'Whisper',
    stats: { PILOT: 3, GUNS: 3, TRADE: 1, GRIT: 1, GUILE: 4 },
    ideal: 'Perfection',
    bond: 'Loyal to the Space Dragons',
    flaw: 'Vengeful',
    flawDc: 12,
    tier: 4,
  },
  {
    id: 'npc-cargo-king',
    name: 'Cargo King',
    shipName: 'Fat Profit',
    stats: { PILOT: 1, GUNS: 0, TRADE: 5, GRIT: 1, GUILE: 2 },
    ideal: 'Wealth',
    bond: 'Loyal to the Astro League',
    flaw: 'Cowardly',
    flawDc: 13,
    tier: 3,
  },
  {
    id: 'npc-lucky-seven',
    name: 'Lucky Seven',
    shipName: 'Jackpot',
    stats: { PILOT: 2, GUNS: 1, TRADE: 2, GRIT: 0, GUILE: 4 },
    ideal: 'Thrill',
    bond: 'No loyalties, only the next hand',
    flaw: 'Compulsive Gambler',
    flawDc: 16,
    tier: 2,
  },
  {
    id: 'npc-admiral-stern',
    name: 'Admiral Stern',
    shipName: 'Iron Curtain',
    stats: { PILOT: 3, GUNS: 3, TRADE: 2, GRIT: 4, GUILE: 0 },
    ideal: 'Order',
    bond: 'Protects the Astro League',
    flaw: 'Overcautious',
    flawDc: 10,
    tier: 5,
  },
  {
    id: 'npc-rattlesnake',
    name: 'Rattlesnake',
    shipName: 'Fang',
    stats: { PILOT: 2, GUNS: 3, TRADE: 3, GRIT: 2, GUILE: 1 },
    ideal: 'Profit',
    bond: 'Loyal to the Warlord Confed',
    flaw: 'Greedy',
    flawDc: 14,
    tier: 3,
  },
  {
    id: 'npc-nova-blitz',
    name: 'Nova Blitz',
    shipName: 'Supernova',
    stats: { PILOT: 4, GUNS: 3, TRADE: 0, GRIT: 2, GUILE: 1 },
    ideal: 'Glory',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Reckless',
    flawDc: 15,
    tier: 3,
  },
  {
    id: 'npc-penny-wise',
    name: 'Penny Wise',
    shipName: 'Thrift Star',
    stats: { PILOT: 1, GUNS: 0, TRADE: 4, GRIT: 2, GUILE: 2 },
    ideal: 'Efficiency',
    bond: 'Loyal to their credits',
    flaw: 'Miserly',
    flawDc: 12,
    tier: 2,
  },
  {
    id: 'npc-black-tide',
    name: 'Black Tide',
    shipName: 'Undertow',
    stats: { PILOT: 2, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 2 },
    ideal: 'Power',
    bond: 'Rules the Space Dragons',
    flaw: 'Cruel',
    flawDc: 12,
    tier: 5,
  },
  {
    id: 'npc-doc-salvage',
    name: 'Doc Salvage',
    shipName: 'Patchwork',
    stats: { PILOT: 3, GUNS: 0, TRADE: 2, GRIT: 4, GUILE: 1 },
    ideal: 'Preservation',
    bond: 'Loyal to the Astro League',
    flaw: 'Savior Complex',
    flawDc: 15,
    tier: 2,
  },
  {
    id: 'npc-wild-card',
    name: 'Wild Card',
    shipName: 'Chaos Theory',
    stats: { PILOT: 3, GUNS: 2, TRADE: 2, GRIT: 1, GUILE: 3 },
    ideal: 'Chaos',
    bond: 'Hates the Astro League',
    flaw: 'Chaotic',
    flawDc: 17,
    tier: 3,
  },
  {
    id: 'npc-frost-helm',
    name: 'Frost Helm',
    shipName: 'Glacier',
    stats: { PILOT: 3, GUNS: 2, TRADE: 3, GRIT: 3, GUILE: 0 },
    ideal: 'Logic',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Rigid',
    flawDc: 10,
    tier: 3,
  },
  {
    id: 'npc-smuggler-ray',
    name: 'Smuggler Ray',
    shipName: 'Ghost Runner',
    stats: { PILOT: 4, GUNS: 1, TRADE: 3, GRIT: 0, GUILE: 4 },
    ideal: 'Freedom',
    bond: 'Loyal to the Space Dragons',
    flaw: 'Paranoid',
    flawDc: 13,
    tier: 3,
  },
  {
    id: 'npc-atlas-prime',
    name: 'Atlas Prime',
    shipName: 'Titan Haul',
    stats: { PILOT: 1, GUNS: 2, TRADE: 4, GRIT: 3, GUILE: 0 },
    ideal: 'Industry',
    bond: 'Loyal to the Warlord Confed',
    flaw: 'Slothful',
    flawDc: 12,
    tier: 3,
  },
  {
    id: 'npc-crimson-ace',
    name: 'Crimson Ace',
    shipName: 'Red Baron',
    stats: { PILOT: 5, GUNS: 4, TRADE: 0, GRIT: 2, GUILE: 1 },
    ideal: 'Excellence',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Prideful',
    flawDc: 13,
    tier: 4,
  },
  {
    id: 'npc-zero-risk',
    name: 'Zero Risk',
    shipName: 'Safe Haven',
    stats: { PILOT: 2, GUNS: 1, TRADE: 4, GRIT: 1, GUILE: 2 },
    ideal: 'Survival',
    bond: 'Loyal to the Astro League',
    flaw: 'Cowardly',
    flawDc: 15,
    tier: 2,
  },
  {
    id: 'npc-neon-fox',
    name: 'Neon Fox',
    shipName: 'Trickster',
    stats: { PILOT: 3, GUNS: 1, TRADE: 3, GRIT: 1, GUILE: 5 },
    ideal: 'Advantage',
    bond: 'Loyal to no one',
    flaw: 'Treacherous',
    flawDc: 14,
    tier: 4,
  },
  {
    id: 'npc-warp-hound',
    name: 'Warp Hound',
    shipName: 'Lightchaser',
    stats: { PILOT: 5, GUNS: 0, TRADE: 1, GRIT: 3, GUILE: 1 },
    ideal: 'Discovery',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Wanderlust',
    flawDc: 14,
    tier: 3,
  },
  {
    id: 'npc-gold-rush',
    name: 'Gold Rush',
    shipName: 'Vault Breaker',
    stats: { PILOT: 1, GUNS: 2, TRADE: 5, GRIT: 2, GUILE: 2 },
    ideal: 'Opulence',
    bond: 'Loyal to the Warlord Confed',
    flaw: 'Greedy',
    flawDc: 15,
    tier: 4,
  },
  {
    id: 'npc-stellar-monk',
    name: 'Stellar Monk',
    shipName: 'Zen Drifter',
    stats: { PILOT: 3, GUNS: 0, TRADE: 3, GRIT: 4, GUILE: 2 },
    ideal: 'Balance',
    bond: 'Loyal to the Space Dragons',
    flaw: 'Pacifist',
    flawDc: 8,
    tier: 3,
  },
  // The 10 New Cast Members
  {
    id: 'npc-void-whisper',
    name: 'Void Whisper',
    shipName: 'Dark Psalm',
    stats: { PILOT: 2, GUNS: 2, TRADE: 0, GRIT: 5, GUILE: 3 },
    ideal: 'Ascension',
    bond: 'Loyal to the Nemesis Signal',
    flaw: 'Zealous',
    flawDc: 14,
    tier: 4,
  },
  {
    id: 'npc-the-broker',
    name: 'The Broker',
    shipName: 'Information Age',
    stats: { PILOT: 1, GUNS: 0, TRADE: 5, GRIT: 1, GUILE: 5 },
    ideal: 'Knowledge',
    bond: "Owns everyone's secrets",
    flaw: 'Manipulative',
    flawDc: 12,
    tier: 4,
  },
  {
    id: 'npc-rust-bucket',
    name: 'Rust Bucket',
    shipName: 'Junk Heap',
    stats: { PILOT: 2, GUNS: 1, TRADE: 3, GRIT: 4, GUILE: 1 },
    ideal: 'Utility',
    bond: 'Protects their stash',
    flaw: 'Hoarder',
    flawDc: 13,
    tier: 1,
  },
  {
    id: 'npc-star-gazer',
    name: 'Star Gazer',
    shipName: 'Observatory',
    stats: { PILOT: 4, GUNS: 0, TRADE: 1, GRIT: 2, GUILE: 1 },
    ideal: 'Truth',
    bond: 'Loyal to the cosmos',
    flaw: 'Distracted',
    flawDc: 15,
    tier: 1,
  },
  {
    id: 'npc-the-warden',
    name: 'The Warden',
    shipName: 'Lockdown',
    stats: { PILOT: 3, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 0 },
    ideal: 'Justice',
    bond: 'Hunts for the Astro League',
    flaw: 'Relentless',
    flawDc: 13,
    tier: 4,
  },
  {
    id: 'npc-nebula-rose',
    name: 'Nebula Rose',
    shipName: 'Stardust',
    stats: { PILOT: 2, GUNS: 1, TRADE: 4, GRIT: 1, GUILE: 4 },
    ideal: 'Beauty',
    bond: 'Loves high society',
    flaw: 'Vain',
    flawDc: 12,
    tier: 3,
  },
  {
    id: 'npc-the-phantom',
    name: 'The Phantom',
    shipName: 'Ectoplasm',
    stats: { PILOT: 5, GUNS: 2, TRADE: 0, GRIT: 3, GUILE: 4 },
    ideal: 'Mystery',
    bond: 'Loyal to the unknown',
    flaw: 'Enigmatic',
    flawDc: 10,
    tier: 5,
  },
  {
    id: 'npc-crash-override',
    name: 'Crash Override',
    shipName: 'Syntax Error',
    stats: { PILOT: 3, GUNS: 1, TRADE: 2, GRIT: 1, GUILE: 5 },
    ideal: 'Control',
    bond: 'Loyal to the datastream',
    flaw: 'Arrogant',
    flawDc: 13,
    tier: 3,
  },
  {
    id: 'npc-the-chef',
    name: 'The Chef',
    shipName: 'Bistro',
    stats: { PILOT: 2, GUNS: 1, TRADE: 4, GRIT: 3, GUILE: 2 },
    ideal: 'Flavor',
    bond: 'Feeds the rim',
    flaw: 'Perfectionist',
    flawDc: 12,
    tier: 2,
  },
  {
    id: 'npc-junk-lord',
    name: 'Junk Lord',
    shipName: 'Scrap Iron',
    stats: { PILOT: 1, GUNS: 3, TRADE: 3, GRIT: 4, GUILE: 1 },
    ideal: 'Possession',
    bond: 'Ruler of the scrap yards',
    flaw: 'Possessive',
    flawDc: 13,
    tier: 3,
  },
];

export const ANONYMOUS_INTERCEPTORS: AnonymousInterceptorProfile[] = [
  {
    id: 'anon-pirate-1',
    kind: 'PIRATE',
    rosterIndex: 1,
    name: 'K)(akj',
    shipName: 'K1++++',
    shipClass: 'Maligna Bat',
    homeSystem: 'Pollux-7',
    stats: { PILOT: 1, GUNS: 0, TRADE: 0, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-pirate-2',
    kind: 'PIRATE',
    rosterIndex: 2,
    name: 'K)(ych',
    shipName: 'K2@@@@',
    shipClass: 'Maligna Cat',
    homeSystem: 'Denebola-5',
    stats: { PILOT: 0, GUNS: 0, TRADE: 0, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-pirate-3',
    kind: 'PIRATE',
    rosterIndex: 3,
    name: 'K)(sfy',
    shipName: 'K3####',
    shipClass: 'Maligna Rat',
    homeSystem: 'Denebola-5',
    stats: { PILOT: 0, GUNS: 0, TRADE: 1, GRIT: 1, GUILE: 1 },
    tier: 2,
  },
  {
    id: 'anon-pirate-4',
    kind: 'PIRATE',
    rosterIndex: 4,
    name: 'K)(sdf',
    shipName: 'K4$$$$',
    shipClass: 'Maligna Tat',
    homeSystem: 'Aldebaran-1',
    stats: { PILOT: 0, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 2,
  },
  {
    id: 'anon-pirate-5',
    kind: 'PIRATE',
    rosterIndex: 5,
    name: 'K)(ssf',
    shipName: 'K5%%%%',
    shipClass: 'Maligna Vat',
    homeSystem: 'Altair-3',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 3,
  },
  {
    id: 'anon-pirate-6',
    kind: 'PIRATE',
    rosterIndex: 6,
    name: 'K)(dfy',
    shipName: 'K6^^^^',
    shipClass: 'Maligna Wat',
    homeSystem: 'Altair-3',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 2 },
    tier: 3,
  },
  {
    id: 'anon-pirate-7',
    kind: 'PIRATE',
    rosterIndex: 7,
    name: 'K)(dsh',
    shipName: 'K7&&&&',
    shipClass: 'Maligna Xat',
    homeSystem: 'Pollux-7',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 2 },
    tier: 4,
  },
  {
    id: 'anon-pirate-8',
    kind: 'PIRATE',
    rosterIndex: 8,
    name: 'K)(ech',
    shipName: 'K8****',
    shipClass: 'Maligna Yat',
    homeSystem: 'Aldebaran-1',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 2 },
    tier: 4,
  },
  {
    id: 'anon-pirate-9',
    kind: 'PIRATE',
    rosterIndex: 9,
    name: 'K)(chy',
    shipName: 'K9((((',
    shipClass: 'Maligna Zat',
    homeSystem: 'Denebola-5',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 2 },
    tier: 5,
  },
  {
    id: 'anon-patrol-1',
    kind: 'PATROL',
    rosterIndex: 1,
    name: 'Lt.Savage',
    shipName: 'SP1.Thor',
    shipClass: 'SLOOP',
    homeSystem: 'Procyon-5',
    stats: { PILOT: 1, GUNS: 0, TRADE: 1, GRIT: 0, GUILE: 0 },
    tier: 1,
  },
  {
    id: 'anon-patrol-2',
    kind: 'PATROL',
    rosterIndex: 2,
    name: 'Cmdr.Strong',
    shipName: 'SP2.Hercules',
    shipClass: 'CUTTER',
    homeSystem: 'Mira-9',
    stats: { PILOT: 0, GUNS: 0, TRADE: 1, GRIT: 0, GUILE: 0 },
    tier: 1,
  },
  {
    id: 'anon-patrol-3',
    kind: 'PATROL',
    rosterIndex: 3,
    name: 'Como.Brainerd',
    shipName: 'SP3.Fearless',
    shipClass: 'BARK',
    homeSystem: 'Fomalhaut-2',
    stats: { PILOT: 0, GUNS: 1, TRADE: 1, GRIT: 0, GUILE: 0 },
    tier: 2,
  },
  {
    id: 'anon-patrol-4',
    kind: 'PATROL',
    rosterIndex: 4,
    name: 'Capt.Brutus',
    shipName: 'SP4.Darkover',
    shipClass: 'BRIGANTINE',
    homeSystem: 'Procyon-5',
    stats: { PILOT: 0, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 2,
  },
  {
    id: 'anon-patrol-5',
    kind: 'PATROL',
    rosterIndex: 5,
    name: 'Capt.Armand',
    shipName: 'SP5.Courageous',
    shipClass: 'CORVETTE',
    homeSystem: 'Regulus-6',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 3,
  },
  {
    id: 'anon-patrol-6',
    kind: 'PATROL',
    rosterIndex: 6,
    name: 'Capt.Bouchet',
    shipName: 'SP6.Firedrake',
    shipClass: 'DESTROYER',
    homeSystem: 'Pollux-7',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 3,
  },
  {
    id: 'anon-patrol-7',
    kind: 'PATROL',
    rosterIndex: 7,
    name: 'Capt.Brax',
    shipName: 'SP7.Victorious',
    shipClass: 'CRUISER',
    homeSystem: 'Procyon-5',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 4,
  },
  {
    id: 'anon-patrol-8',
    kind: 'PATROL',
    rosterIndex: 8,
    name: 'Adm.Wong',
    shipName: 'SP8.Meritorious',
    shipClass: 'FRIGATE',
    homeSystem: 'Deneb-4',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 4,
  },
  {
    id: 'anon-patrol-9',
    kind: 'PATROL',
    rosterIndex: 9,
    name: 'Adm.Hutchins',
    shipName: 'SP9.Incredible',
    shipClass: 'BATTLESHIP',
    homeSystem: 'Aldebaran-1',
    stats: { PILOT: 1, GUNS: 2, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 4,
  },
  {
    id: 'anon-patrol-10',
    kind: 'PATROL',
    rosterIndex: 10,
    name: 'Adm.Bruiser',
    shipName: 'SPX.Inferno',
    shipClass: 'DEATHSTAR',
    homeSystem: 'Arcturus-6',
    stats: { PILOT: 2, GUNS: 2, TRADE: 1, GRIT: 2, GUILE: 0 },
    tier: 5,
  },
  {
    id: 'anon-patrol-11',
    kind: 'PATROL',
    rosterIndex: 11,
    name: 'Adm.Borgia',
    shipName: 'SPZ.Infinity',
    shipClass: 'INFINITY',
    homeSystem: 'Altair-3',
    stats: { PILOT: 2, GUNS: 3, TRADE: 1, GRIT: 3, GUILE: 0 },
    tier: 5,
  },
  {
    id: 'anon-rim-pirate-1',
    kind: 'RIM_PIRATE',
    rosterIndex: 1,
    name: 'RP-Black Bart',
    shipName: 'Gypsy Lee',
    shipClass: 'Sailfish',
    homeSystem: 'Antares-5',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-rim-pirate-2',
    kind: 'RIM_PIRATE',
    rosterIndex: 2,
    name: 'RP-Blackbeard',
    shipName: 'Buccaneer',
    shipClass: 'Swordfish',
    homeSystem: 'Capella-4',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-rim-pirate-3',
    kind: 'RIM_PIRATE',
    rosterIndex: 3,
    name: 'RP-Anne Bonny',
    shipName: 'Red Witch',
    shipClass: 'Barracuda',
    homeSystem: 'Polaris-1',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-rim-pirate-4',
    kind: 'RIM_PIRATE',
    rosterIndex: 4,
    name: 'RP-Mary Read',
    shipName: 'Sea Witch',
    shipClass: 'Hammerhead',
    homeSystem: 'Mizar-9',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-rim-pirate-5',
    kind: 'RIM_PIRATE',
    rosterIndex: 5,
    name: 'RP-Long Ben',
    shipName: 'Marauder',
    shipClass: 'Moray',
    homeSystem: 'Achernar-5',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 2,
  },
  {
    id: 'anon-rim-pirate-6',
    kind: 'RIM_PIRATE',
    rosterIndex: 6,
    name: 'RP-Henry Morgan',
    shipName: 'Rascal',
    shipClass: 'Moray',
    homeSystem: 'Algol-2',
    stats: { PILOT: 2, GUNS: 2, TRADE: 1, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-rim-pirate-7',
    kind: 'RIM_PIRATE',
    rosterIndex: 7,
    name: 'RP-Piet Nym',
    shipName: 'Golden Fleece',
    shipClass: 'Mako',
    homeSystem: 'Antares-5',
    stats: { PILOT: 2, GUNS: 2, TRADE: 0, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-rim-pirate-8',
    kind: 'RIM_PIRATE',
    rosterIndex: 8,
    name: 'RP-Long J.Silver',
    shipName: 'Golden Hiney',
    shipClass: 'Thresher',
    homeSystem: 'Capella-4',
    stats: { PILOT: 2, GUNS: 2, TRADE: 0, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-rim-pirate-9',
    kind: 'RIM_PIRATE',
    rosterIndex: 9,
    name: 'RP-Peg-Leg Smith',
    shipName: 'She Devil',
    shipClass: 'Marlin',
    homeSystem: 'Polaris-1',
    stats: { PILOT: 2, GUNS: 2, TRADE: 1, GRIT: 2, GUILE: 2 },
    tier: 3,
  },
  {
    id: 'anon-rim-pirate-10',
    kind: 'RIM_PIRATE',
    rosterIndex: 10,
    name: "RP-Cap'n Jack",
    shipName: 'Fancy Dancy',
    shipClass: 'Orca',
    homeSystem: 'Mizar-9',
    stats: { PILOT: 3, GUNS: 3, TRADE: 0, GRIT: 3, GUILE: 2 },
    tier: 3,
  },
  {
    id: 'anon-rim-pirate-11',
    kind: 'RIM_PIRATE',
    rosterIndex: 11,
    name: 'RP-Lord Tim',
    shipName: 'Fauntleroy',
    shipClass: 'Manta',
    homeSystem: 'Achernar-5',
    stats: { PILOT: 3, GUNS: 3, TRADE: 0, GRIT: 3, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-rim-pirate-12',
    kind: 'RIM_PIRATE',
    rosterIndex: 12,
    name: "RP-Cap'n Ahab",
    shipName: 'Moby Dick',
    shipClass: 'Giant Squid',
    homeSystem: 'Algol-2',
    stats: { PILOT: 3, GUNS: 3, TRADE: 1, GRIT: 3, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-rim-pirate-13',
    kind: 'RIM_PIRATE',
    rosterIndex: 13,
    name: 'RP-Dirty Jack',
    shipName: 'Brass Tack',
    shipClass: 'Halibut',
    homeSystem: 'Antares-5',
    stats: { PILOT: 3, GUNS: 3, TRADE: 0, GRIT: 3, GUILE: 3 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-14',
    kind: 'RIM_PIRATE',
    rosterIndex: 14,
    name: 'RP-Good John',
    shipName: 'Coppersides',
    shipClass: 'Flounder',
    homeSystem: 'Capella-4',
    stats: { PILOT: 4, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 3 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-15',
    kind: 'RIM_PIRATE',
    rosterIndex: 15,
    name: 'RP-Messy Frank',
    shipName: 'Silversides',
    shipClass: 'Sea Bass',
    homeSystem: 'Polaris-1',
    stats: { PILOT: 4, GUNS: 4, TRADE: 1, GRIT: 4, GUILE: 3 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-16',
    kind: 'RIM_PIRATE',
    rosterIndex: 16,
    name: 'RP-Farragut',
    shipName: 'Lady Luck',
    shipClass: 'Lionfish',
    homeSystem: 'Mizar-9',
    stats: { PILOT: 4, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-17',
    kind: 'RIM_PIRATE',
    rosterIndex: 17,
    name: 'RP-Van Mere',
    shipName: "Witch's Brew",
    shipClass: 'Tetrapod',
    homeSystem: 'Achernar-5',
    stats: { PILOT: 4, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-18',
    kind: 'RIM_PIRATE',
    rosterIndex: 18,
    name: 'RP-Van Slab',
    shipName: "Devil's Spout",
    shipClass: 'Gastropod',
    homeSystem: 'Algol-2',
    stats: { PILOT: 5, GUNS: 5, TRADE: 1, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
  {
    id: 'anon-rim-pirate-19',
    kind: 'RIM_PIRATE',
    rosterIndex: 19,
    name: 'RP-Innkeeper',
    shipName: 'Purple Smaze',
    shipClass: 'Euchuroidea',
    homeSystem: 'Antares-5',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
  {
    id: 'anon-rim-pirate-20',
    kind: 'RIM_PIRATE',
    rosterIndex: 20,
    name: 'RP-Polly Nyces',
    shipName: 'Moon Snail',
    shipClass: 'Starfish',
    homeSystem: 'Capella-4',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
  {
    id: 'anon-rim-pirate-21',
    kind: 'RIM_PIRATE',
    rosterIndex: 21,
    name: 'RP-Alienator',
    shipName: 'PREDATOR',
    shipClass: 'Symbiote',
    homeSystem: 'Algol-2',
    stats: { PILOT: 5, GUNS: 5, TRADE: 1, GRIT: 5, GUILE: 5 },
    tier: 5,
  },
  {
    id: 'anon-brigand-1',
    kind: 'BRIGAND',
    rosterIndex: 1,
    name: 'Cruncher',
    shipName: 'Big Mac',
    shipClass: 'N1.Sloop',
    homeSystem: 'Sun-3',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-brigand-2',
    kind: 'BRIGAND',
    rosterIndex: 2,
    name: 'Chomper',
    shipName: 'Nugget',
    shipClass: 'N1.Sloop',
    homeSystem: 'Aldebaran-1',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-brigand-3',
    kind: 'BRIGAND',
    rosterIndex: 3,
    name: 'Stomper',
    shipName: 'Fish Stix',
    shipClass: 'N1.Sloop',
    homeSystem: 'Altair-3',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-brigand-4',
    kind: 'BRIGAND',
    rosterIndex: 4,
    name: 'Bruiser',
    shipName: 'Fries',
    shipClass: 'N1.Sloop',
    homeSystem: 'Arcturus-6',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-brigand-5',
    kind: 'BRIGAND',
    rosterIndex: 5,
    name: 'Bonker',
    shipName: 'Pop Tart',
    shipClass: 'N1.Sloop',
    homeSystem: 'Deneb-4',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-brigand-6',
    kind: 'BRIGAND',
    rosterIndex: 6,
    name: 'Blaster',
    shipName: 'Twinkie',
    shipClass: 'N1.Sloop',
    homeSystem: 'Denebola-5',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-brigand-7',
    kind: 'BRIGAND',
    rosterIndex: 7,
    name: 'Bumper',
    shipName: 'Ho-Ho',
    shipClass: 'N1.Sloop',
    homeSystem: 'Fomalhaut-2',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-brigand-8',
    kind: 'BRIGAND',
    rosterIndex: 8,
    name: 'Buster',
    shipName: 'Jelly Bean',
    shipClass: 'N1.Sloop',
    homeSystem: 'Mira-9',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-brigand-9',
    kind: 'BRIGAND',
    rosterIndex: 9,
    name: 'Booster',
    shipName: 'Jube-Jube',
    shipClass: 'N1.Sloop',
    homeSystem: 'Pollux-7',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-brigand-10',
    kind: 'BRIGAND',
    rosterIndex: 10,
    name: 'Bugster',
    shipName: 'Taco',
    shipClass: 'N1.Sloop',
    homeSystem: 'Procyon-5',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-brigand-11',
    kind: 'BRIGAND',
    rosterIndex: 11,
    name: 'Bammer',
    shipName: 'Chips',
    shipClass: 'N1.Sloop',
    homeSystem: 'Regulus-6',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-brigand-12',
    kind: 'BRIGAND',
    rosterIndex: 12,
    name: 'Bummer',
    shipName: 'McDLT',
    shipClass: 'N1.Sloop',
    homeSystem: 'Rigel-8',
    stats: { PILOT: 1, GUNS: 1, TRADE: 2, GRIT: 1, GUILE: 5 },
    tier: 5,
  },
  {
    id: 'anon-reptiloid-1',
    kind: 'REPTILOID',
    rosterIndex: 1,
    name: 'Admiral Assss',
    shipName: 'SS Anaconda',
    shipClass: 'S1-Snake',
    homeSystem: 'NGC-44',
    stats: { PILOT: 5, GUNS: 0, TRADE: 0, GRIT: 1, GUILE: 2 },
    tier: 1,
  },
  {
    id: 'anon-reptiloid-2',
    kind: 'REPTILOID',
    rosterIndex: 2,
    name: 'Admiral Bssss',
    shipName: 'SS Bull',
    shipClass: 'S2-Snake',
    homeSystem: 'NGC-55',
    stats: { PILOT: 5, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 2 },
    tier: 1,
  },
  {
    id: 'anon-reptiloid-3',
    kind: 'REPTILOID',
    rosterIndex: 3,
    name: 'Admiral Cssss',
    shipName: 'SS Copperhead',
    shipClass: 'S3-Snake',
    homeSystem: 'NGC-66',
    stats: { PILOT: 5, GUNS: 1, TRADE: 0, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-reptiloid-4',
    kind: 'REPTILOID',
    rosterIndex: 4,
    name: 'Admiral Dssss',
    shipName: 'SS Fer-de-Lance',
    shipClass: 'S4-Snake',
    homeSystem: 'NGC-77',
    stats: { PILOT: 4, GUNS: 2, TRADE: 0, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-reptiloid-5',
    kind: 'REPTILOID',
    rosterIndex: 5,
    name: 'Admiral Essss',
    shipName: 'SS Garter',
    shipClass: 'S5-Snake',
    homeSystem: 'NGC-88',
    stats: { PILOT: 4, GUNS: 2, TRADE: 0, GRIT: 3, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-reptiloid-6',
    kind: 'REPTILOID',
    rosterIndex: 6,
    name: 'Admiral Fssss',
    shipName: 'SS Indigo',
    shipClass: 'S6-Snake',
    homeSystem: 'NGC-99',
    stats: { PILOT: 4, GUNS: 3, TRADE: 0, GRIT: 3, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-reptiloid-7',
    kind: 'REPTILOID',
    rosterIndex: 7,
    name: 'Admiral Gssss',
    shipName: 'SS Viper',
    shipClass: 'S7-Snake',
    homeSystem: 'NGC-44',
    stats: { PILOT: 4, GUNS: 3, TRADE: 0, GRIT: 4, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-reptiloid-8',
    kind: 'REPTILOID',
    rosterIndex: 8,
    name: 'Admiral Hssss',
    shipName: 'SS Coral',
    shipClass: 'S8-Snake',
    homeSystem: 'NGC-55',
    stats: { PILOT: 5, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 3 },
    tier: 4,
  },
  {
    id: 'anon-reptiloid-9',
    kind: 'REPTILOID',
    rosterIndex: 9,
    name: 'Admiral Issss',
    shipName: 'SS Rattler',
    shipClass: 'S9-Snake',
    homeSystem: 'NGC-66',
    stats: { PILOT: 5, GUNS: 4, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-reptiloid-10',
    kind: 'REPTILOID',
    rosterIndex: 10,
    name: 'Admiral Kssss',
    shipName: 'SS Asp',
    shipClass: 'SX-Snake',
    homeSystem: 'NGC-77',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-reptiloid-11',
    kind: 'REPTILOID',
    rosterIndex: 11,
    name: 'Admiral Lssss',
    shipName: 'SS Adder',
    shipClass: 'SY-Snake',
    homeSystem: 'NGC-88',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
  {
    id: 'anon-reptiloid-12',
    kind: 'REPTILOID',
    rosterIndex: 12,
    name: 'Admiral Mssss',
    shipName: 'SS Cobra',
    shipClass: 'SZ-Snake',
    homeSystem: 'NGC-99',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
];
