import { StatBlock } from './stats.js';
import { BondHook } from './disposition.js';

export type PowerTier = 1 | 2 | 3 | 4 | 5;

export type AnonymousInterceptorKind = 'PIRATE' | 'PATROL' | 'RIM_PIRATE' | 'BRIGAND' | 'REPTILOID';

export interface AnonymousInterceptorProfile {
  id: string;
  kind: AnonymousInterceptorKind;
  rosterIndex: number;
  name: string;
  shipName: string;
  shipClass: string;
  homeSystem: string;
  stats: StatBlock;
  tier: PowerTier;
}

export type NpcArchetype = 'trader' | 'fighter' | 'explorer' | 'smuggler' | 'gambler' | 'veteran';

export interface NpcProfile {
  id: string;
  name: string;
  shipName: string;
  stats: StatBlock;
  ideal: string;
  bond: string;
  flaw: string;
  /** Resist the flaw on d20 >= flawDc (disciplined = low, volatile = high). */
  flawDc: number;
  /** Power tier: 1 = mudlark, 5 = legend (PRD §6). */
  tier: PowerTier;
  /** N4 · The captain's playstyle. It does not REPLACE {@link ideal} — it biases
   *  it, through `ARCHETYPE_INTENT_MULTIPLIERS` in ideals.ts. See the curation
   *  note above {@link NPC_PROFILES} for how the 30 were assigned. */
  archetype: NpcArchetype;
  /** T-1204: the dusk Bond intervention this NPC performs when the player has
   *  earned their standing. Present only on the handful of profiles whose Bond
   *  implies a player-facing obligation; the beat (drive-off / fuel-gift) is the
   *  one their Bond fictionally supports. Engine reader: the bond hook in
   *  `day.ts` endDay. */
  bondHook?: BondHook;
}

/**
 * N4 · THE ARCHETYPE ASSIGNMENT IS HAND-CURATED, and that is a ruling, not a
 * preference (docs/NPC_REDESIGN.md, N4 RULING 2: *"archetypes are hand-curated
 * from each captain's stats / ideal / bond, with a floor guaranteeing every
 * archetype has enough members for its branch to be live and measurable"*).
 *
 * WHY THE RULING EXISTS — the first attempt generated the field with a one-off
 * regex script whose first-match branch chain starved the last two archetypes,
 * leaving **0 veterans and 1 smuggler** across these 30. A branch with no
 * members is not a design decision, it is dead code that reads as one, and no
 * sweep can measure it. The floor is what makes each branch gradeable.
 *
 * THE DISTRIBUTION, pinned by `cast.test.ts` so it cannot quietly starve again:
 * trader 6 · fighter 6 · explorer 5 · veteran 5 · gambler 4 · smuggler 4 = 30.
 *
 * HOW A CAPTAIN WAS PLACED — read in this order, and the ORDER is not a
 * precedence chain (that is what went wrong the first time), it is what each
 * archetype means:
 *   · **trader**   — TRADE 4+ under a commerce Ideal (Wealth / Profit / Opulence
 *                    / Industry). The manifest board is the whole day.
 *   · **fighter**  — GUNS at or near the top of the line under a martial Ideal
 *                    (Dominance / Glory / Power / Excellence), TRADE 0–1.
 *   · **explorer** — PILOT top of the line with a Travel-heavy Ideal (Discovery /
 *                    Truth / Freedom / Mystery) and a bond pointed outward
 *                    ("loyal to the cosmos", "the open stars", "the next horizon").
 *   · **smuggler** — a bond outside the lawful factions (the rim, the shadows, a
 *                    faction they hate) plus the means to work it: TRADE to move
 *                    the cargo or PILOT to outrun what objects.
 *   · **gambler**  — GUILE 4+, or a volatile flaw (Reckless / Impulsive /
 *                    Arrogant / Treacherous) on a line with no dominant stat.
 *   · **veteran**  — a career rather than a specialism: tier 3+, no stat above 4,
 *                    at least three stats filled, and a disciplined flawDc. These
 *                    are the captains who play the whole loop.
 * Where a captain's assignment is not obvious from their line, the reason is
 * written at their own entry below rather than left to be re-derived.
 *
 * Three assignments are FIXED by the owner's ruling, which worked their
 * arithmetic out by hand: **Iron Vex fighter**, **Cargo King trader**, **Zero
 * Risk trader**. Changing one of those three silently invalidates a recorded
 * worked example; change the ruling first.
 */
export const NPC_PROFILES: NpcProfile[] = [
  // The Original 20 (minus 8 extracted) = 12
  {
    id: 'npc-iron-vex',
    name: 'Iron Vex',
    shipName: 'Hammerfall',
    stats: { PILOT: 2, GUNS: 4, TRADE: 0, GRIT: 3, GUILE: 0 },
    ideal: 'Dominance',
    bond: 'Loyal to the Warlord Confed',
    flaw: 'Bloodthirsty',
    flawDc: 14,
    tier: 3,
    archetype: 'fighter',
  },
  {
    id: 'npc-cargo-king',
    name: 'Cargo King',
    shipName: 'Fat Profit',
    stats: { PILOT: 1, GUNS: 0, TRADE: 5, GRIT: 1, GUILE: 2 },
    ideal: 'Wealth',
    bond: 'Loyal to the Astro League',
    flaw: 'Cowardly',
    flawDc: 13,
    tier: 3,
    archetype: 'trader',
  },
  {
    id: 'npc-admiral-stern',
    name: 'Admiral Stern',
    shipName: 'Iron Curtain',
    stats: { PILOT: 3, GUNS: 3, TRADE: 2, GRIT: 4, GUILE: 0 },
    ideal: 'Order',
    bond: 'Protects the Astro League',
    flaw: 'Overcautious',
    flawDc: 10,
    tier: 5,
    /** N4 · tier 5, no stat above 4 and four of five filled, flawDc 10 (the most disciplined
     *  captain on the roster): the broad, seasoned game the archetype names */
    archetype: 'veteran',
    bondHook: { beat: 'drive-off', activateAt: 3, dc: 12 },
  },
  {
    id: 'npc-nova-blitz',
    name: 'Nova Blitz',
    shipName: 'Supernova',
    stats: { PILOT: 4, GUNS: 3, TRADE: 0, GRIT: 2, GUILE: 1 },
    ideal: 'Glory',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Reckless',
    flawDc: 15,
    tier: 3,
    archetype: 'fighter',
  },
  {
    id: 'npc-black-tide',
    name: 'Black Tide',
    shipName: 'Undertow',
    stats: { PILOT: 2, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 2 },
    ideal: 'Power',
    bond: 'Rules the Space Dragons',
    flaw: 'Cruel',
    flawDc: 12,
    tier: 5,
    /** N4 · tier 5 and rules a faction — a career, not a specialism; GUNS 4 + GRIT 4 + GUILE 2
     *  fights, endures and negotiates, which is the veteran stance exactly */
    archetype: 'veteran',
  },
  {
    id: 'npc-frost-helm',
    name: 'Frost Helm',
    shipName: 'Glacier',
    stats: { PILOT: 3, GUNS: 2, TRADE: 3, GRIT: 3, GUILE: 0 },
    ideal: 'Logic',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Rigid',
    flawDc: 10,
    tier: 3,
    /** N4 · the flattest stat line in the cast (3/2/3/3/0) under a Logic ideal and flawDc 10 —
     *  a methodical all-rounder, not a specialist trader */
    archetype: 'veteran',
  },
  {
    id: 'npc-atlas-prime',
    name: 'Atlas Prime',
    shipName: 'Titan Haul',
    stats: { PILOT: 1, GUNS: 2, TRADE: 4, GRIT: 3, GUILE: 0 },
    ideal: 'Industry',
    bond: 'Loyal to the Warlord Confed',
    flaw: 'Slothful',
    flawDc: 12,
    tier: 3,
    archetype: 'trader',
  },
  {
    id: 'npc-crimson-ace',
    name: 'Crimson Ace',
    shipName: 'Red Baron',
    stats: { PILOT: 5, GUNS: 4, TRADE: 0, GRIT: 2, GUILE: 1 },
    ideal: 'Excellence',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Prideful',
    flawDc: 13,
    tier: 4,
    archetype: 'fighter',
  },
  {
    id: 'npc-zero-risk',
    name: 'Zero Risk',
    shipName: 'Safe Haven',
    stats: { PILOT: 2, GUNS: 1, TRADE: 4, GRIT: 1, GUILE: 2 },
    ideal: 'Survival',
    bond: 'Loyal to the Astro League',
    flaw: 'Cowardly',
    flawDc: 15,
    tier: 2,
    archetype: 'trader',
  },
  {
    id: 'npc-neon-fox',
    name: 'Neon Fox',
    shipName: 'Trickster',
    stats: { PILOT: 3, GUNS: 1, TRADE: 3, GRIT: 1, GUILE: 5 },
    ideal: 'Advantage',
    bond: 'Loyal to no one',
    flaw: 'Treacherous',
    flawDc: 14,
    tier: 4,
    archetype: 'gambler',
  },
  {
    id: 'npc-warp-hound',
    name: 'Warp Hound',
    shipName: 'Lightchaser',
    stats: { PILOT: 5, GUNS: 0, TRADE: 1, GRIT: 3, GUILE: 1 },
    ideal: 'Discovery',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Wanderlust',
    flawDc: 14,
    tier: 3,
    archetype: 'explorer',
  },
  {
    id: 'npc-gold-rush',
    name: 'Gold Rush',
    shipName: 'Vault Breaker',
    stats: { PILOT: 1, GUNS: 2, TRADE: 5, GRIT: 2, GUILE: 2 },
    ideal: 'Opulence',
    bond: 'Loyal to the Warlord Confed',
    flaw: 'Greedy',
    flawDc: 15,
    tier: 4,
    archetype: 'trader',
  },
  // The 10 New Cast Members (minus 3 extracted) = 7
  {
    id: 'npc-star-gazer',
    name: 'Star Gazer',
    shipName: 'Observatory',
    stats: { PILOT: 4, GUNS: 0, TRADE: 1, GRIT: 2, GUILE: 1 },
    ideal: 'Truth',
    bond: 'Loyal to the cosmos',
    flaw: 'Distracted',
    flawDc: 15,
    tier: 1,
    archetype: 'explorer',
  },
  {
    id: 'npc-the-warden',
    name: 'The Warden',
    shipName: 'Lockdown',
    stats: { PILOT: 3, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 0 },
    ideal: 'Justice',
    bond: 'Hunts for the Astro League',
    flaw: 'Relentless',
    flawDc: 13,
    tier: 4,
    /** N4 · a tier-4 bounty hunter who hunts FOR an institution: the roster's natural
     *  deed-chaser, which is what the sim's veteran policy is. Justice vetoes Trade outright,
     *  so the blend leaves them on Combat and Patrol without an archetype needing to say so */
    archetype: 'veteran',
  },
  {
    id: 'npc-nebula-rose',
    name: 'Nebula Rose',
    shipName: 'Stardust',
    stats: { PILOT: 2, GUNS: 1, TRADE: 4, GRIT: 1, GUILE: 4 },
    ideal: 'Beauty',
    bond: 'Loves high society',
    flaw: 'Vain',
    flawDc: 12,
    tier: 3,
    /** N4 · TRADE 4 beside GUILE 4, a Beauty ideal weighted on Socialize, and a bond that
     *  literally reads "loves high society" — the Hangout is her venue, not the manifest board */
    archetype: 'gambler',
  },
  {
    id: 'npc-the-phantom',
    name: 'The Phantom',
    shipName: 'Ectoplasm',
    stats: { PILOT: 5, GUNS: 2, TRADE: 0, GRIT: 3, GUILE: 4 },
    ideal: 'Mystery',
    bond: 'Loyal to the unknown',
    flaw: 'Enigmatic',
    flawDc: 10,
    tier: 5,
    /** N4 · tier 5, PILOT 5, TRADE 0, and a Mystery ideal already weighted Travel 5 — nothing
     *  about this captain trades, and "loyal to the unknown" is the explorer's remit */
    archetype: 'explorer',
  },
  {
    id: 'npc-crash-override',
    name: 'Crash Override',
    shipName: 'Syntax Error',
    stats: { PILOT: 3, GUNS: 1, TRADE: 2, GRIT: 1, GUILE: 5 },
    ideal: 'Control',
    bond: 'Loyal to the datastream',
    flaw: 'Arrogant',
    flawDc: 13,
    tier: 3,
    archetype: 'gambler',
  },
  {
    id: 'npc-the-chef',
    name: 'The Chef',
    shipName: 'Bistro',
    stats: { PILOT: 2, GUNS: 1, TRADE: 4, GRIT: 3, GUILE: 2 },
    ideal: 'Flavor',
    bond: 'Feeds the rim',
    flaw: 'Perfectionist',
    flawDc: 12,
    tier: 2,
    /** N4 · TRADE 4 with a bond that reads "feeds the rim" — the rim run IS the smuggler's
     *  mechanical signature (`executeTrade`'s rim preference), and this is the captain it was
     *  authored for */
    archetype: 'smuggler',
  },
  {
    id: 'npc-junk-lord',
    name: 'Junk Lord',
    shipName: 'Scrap Iron',
    stats: { PILOT: 1, GUNS: 3, TRADE: 3, GRIT: 4, GUILE: 1 },
    ideal: 'Possession',
    bond: 'Ruler of the scrap yards',
    flaw: 'Possessive',
    flawDc: 13,
    tier: 3,
    /** N4 · GUNS 3, TRADE 3, GRIT 4 under a Possession ideal — a scrapyard baron who fights,
     *  hauls and holds ground rather than doing one of the three */
    archetype: 'veteran',
  },
  // 11 Newly Generated Simulation Characters
  {
    id: 'npc-iron-clad',
    name: 'Iron Clad',
    shipName: 'Dreadnought',
    stats: { PILOT: 2, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 0 },
    ideal: 'Dominance',
    bond: 'Loyal to the Warlord Confed',
    flaw: 'Stubborn',
    flawDc: 14,
    tier: 4,
    archetype: 'fighter',
  },
  {
    id: 'npc-stellar-drift',
    name: 'Stellar Drift',
    shipName: 'Wanderer',
    stats: { PILOT: 4, GUNS: 0, TRADE: 3, GRIT: 1, GUILE: 2 },
    ideal: 'Freedom',
    bond: 'Loyal to the open stars',
    flaw: 'Flighty',
    flawDc: 12,
    tier: 2,
    archetype: 'explorer',
  },
  {
    id: 'npc-void-runner',
    name: 'Void Runner',
    shipName: 'Slipstream',
    stats: { PILOT: 5, GUNS: 1, TRADE: 1, GRIT: 2, GUILE: 1 },
    ideal: 'Thrill',
    bond: 'Hunts the fastest routes',
    flaw: 'Impulsive',
    flawDc: 15,
    tier: 3,
    /** N4 · PILOT 5 and "hunts the fastest routes" on a Thrill ideal: the blockade runner.
     *  TRADE 1 means thin margins, which is the point — the archetype is not a promise of
     *  profit */
    archetype: 'smuggler',
  },
  {
    id: 'npc-crimson-hawk',
    name: 'Crimson Hawk',
    shipName: 'Bloodwing',
    stats: { PILOT: 3, GUNS: 4, TRADE: 0, GRIT: 3, GUILE: 0 },
    ideal: 'Glory',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Reckless',
    flawDc: 13,
    tier: 4,
    archetype: 'fighter',
  },
  {
    id: 'npc-neon-shade',
    name: 'Neon Shade',
    shipName: 'Nightfall',
    stats: { PILOT: 2, GUNS: 2, TRADE: 2, GRIT: 1, GUILE: 3 },
    ideal: 'Mystery',
    bond: 'Loyal to the shadows',
    flaw: 'Paranoid',
    flawDc: 14,
    tier: 2,
    archetype: 'smuggler',
  },
  {
    id: 'npc-dust-devil',
    name: 'Dust Devil',
    shipName: 'Sandstorm',
    stats: { PILOT: 3, GUNS: 1, TRADE: 4, GRIT: 2, GUILE: 0 },
    ideal: 'Profit',
    bond: 'Loyal to the frontier',
    flaw: 'Greedy',
    flawDc: 12,
    tier: 2,
    /** N4 · frontier-loyal, but GUILE 0 — a captain who cannot keep a secret is not a smuggler,
     *  whatever their bond says */
    archetype: 'trader',
  },
  {
    id: 'npc-star-chaser',
    name: 'Star Chaser',
    shipName: 'Comet',
    stats: { PILOT: 4, GUNS: 1, TRADE: 3, GRIT: 1, GUILE: 1 },
    ideal: 'Discovery',
    bond: 'Loyal to the next horizon',
    flaw: 'Distracted',
    flawDc: 11,
    tier: 3,
    archetype: 'explorer',
  },
  {
    id: 'npc-rogue-star',
    name: 'Rogue Star',
    shipName: 'Rebellion',
    stats: { PILOT: 3, GUNS: 3, TRADE: 1, GRIT: 2, GUILE: 1 },
    ideal: 'Chaos',
    bond: 'Hates the Astro League',
    flaw: 'Defiant',
    flawDc: 14,
    tier: 3,
    /** N4 · a Chaos ideal, a Defiant flaw and a bond that HATES the Astro League: runs cargo
     *  past the patrols of the faction they hate. GUNS 3 keeps them dangerous when the run goes
     *  wrong */
    archetype: 'smuggler',
  },
  {
    id: 'npc-plasma-burn',
    name: 'Plasma Burn',
    shipName: 'Scorcher',
    stats: { PILOT: 2, GUNS: 4, TRADE: 0, GRIT: 3, GUILE: 1 },
    ideal: 'Power',
    bond: 'Loyal to chaos',
    flaw: 'Destructive',
    flawDc: 16,
    tier: 3,
    archetype: 'fighter',
  },
  {
    id: 'npc-comet-tail',
    name: 'Comet Tail',
    shipName: 'Icebreaker',
    stats: { PILOT: 3, GUNS: 1, TRADE: 4, GRIT: 2, GUILE: 0 },
    ideal: 'Wealth',
    bond: 'Loyal to the trade routes',
    flaw: 'Miserly',
    flawDc: 12,
    tier: 2,
    archetype: 'trader',
  },
  {
    id: 'npc-solar-flare',
    name: 'Solar Flare',
    shipName: 'Sunspot',
    stats: { PILOT: 4, GUNS: 3, TRADE: 0, GRIT: 2, GUILE: 1 },
    ideal: 'Power',
    bond: 'Loyal to the Rebel Alliance',
    flaw: 'Arrogant',
    flawDc: 13,
    tier: 3,
    /** N4 · the roster's third Glory/Power hotshot with a PILOT 4 / GUNS 3 line; Arrogant, and
     *  the one of the three whose day is a bet rather than a discipline. Keeping all three as
     *  fighters made near-duplicate captains */
    archetype: 'gambler',
  },
];

export const QUEST_PROFILES: NpcProfile[] = [
  {
    id: 'npc-silk-dagger',
    name: 'Silk Dagger',
    shipName: 'Whisper',
    stats: { PILOT: 3, GUNS: 3, TRADE: 1, GRIT: 1, GUILE: 4 },
    ideal: 'Perfection',
    bond: 'Loyal to the Space Dragons',
    flaw: 'Vengeful',
    flawDc: 12,
    tier: 4,
    archetype: 'gambler',
  },
  {
    id: 'npc-lucky-seven',
    name: 'Lucky Seven',
    shipName: 'Jackpot',
    stats: { PILOT: 2, GUNS: 1, TRADE: 2, GRIT: 0, GUILE: 4 },
    ideal: 'Thrill',
    bond: 'No loyalties, only the next hand',
    flaw: 'Compulsive Gambler',
    flawDc: 16,
    tier: 2,
    archetype: 'gambler',
  },
  {
    id: 'npc-rattlesnake',
    name: 'Rattlesnake',
    shipName: 'Fang',
    stats: { PILOT: 2, GUNS: 3, TRADE: 3, GRIT: 2, GUILE: 1 },
    ideal: 'Profit',
    bond: 'Loyal to the Warlord Confed',
    flaw: 'Vengeful',
    flawDc: 14,
    tier: 3,
    archetype: 'trader',
  },
  {
    id: 'npc-penny-wise',
    name: 'Penny Wise',
    shipName: 'Thrift Star',
    stats: { PILOT: 1, GUNS: 0, TRADE: 4, GRIT: 2, GUILE: 2 },
    ideal: 'Efficiency',
    bond: 'Loyal to their credits',
    flaw: 'Miserly',
    flawDc: 12,
    tier: 2,
    archetype: 'trader',
  },
  {
    id: 'npc-doc-salvage',
    name: 'Doc Salvage',
    shipName: 'Patchwork',
    stats: { PILOT: 3, GUNS: 0, TRADE: 2, GRIT: 4, GUILE: 1 },
    ideal: 'Preservation',
    bond: 'Loyal to the Astro League',
    flaw: 'Savior Complex',
    flawDc: 15,
    tier: 2,
    archetype: 'trader',
    bondHook: {
      beat: 'fuel-gift',
      activateAt: 2,
      dc: 8,
      fuelAmount: 50,
      lowFuelThreshold: 150,
      minRescuerFuel: 100,
    },
  },
  {
    id: 'npc-wild-card',
    name: 'Wild Card',
    shipName: 'Chaos Theory',
    stats: { PILOT: 3, GUNS: 2, TRADE: 2, GRIT: 1, GUILE: 3 },
    ideal: 'Chaos',
    bond: 'Hates the Astro League',
    flaw: 'Chaotic',
    flawDc: 17,
    tier: 3,
    archetype: 'gambler',
  },
  {
    id: 'npc-smuggler-ray',
    name: 'Smuggler Ray',
    shipName: 'Ghost Runner',
    stats: { PILOT: 4, GUNS: 1, TRADE: 3, GRIT: 0, GUILE: 4 },
    ideal: 'Freedom',
    bond: 'Loyal to the Space Dragons',
    flaw: 'Paranoid',
    flawDc: 13,
    tier: 3,
    archetype: 'gambler',
  },
  {
    id: 'npc-stellar-monk',
    name: 'Stellar Monk',
    shipName: 'Zen Drifter',
    stats: { PILOT: 3, GUNS: 0, TRADE: 3, GRIT: 4, GUILE: 2 },
    ideal: 'Balance',
    bond: 'Loyal to the Space Dragons',
    flaw: 'Pacifist',
    flawDc: 8,
    tier: 3,
    archetype: 'smuggler',
  },
  {
    id: 'npc-void-whisper',
    name: 'Void Whisper',
    shipName: 'Dark Psalm',
    stats: { PILOT: 2, GUNS: 2, TRADE: 0, GRIT: 5, GUILE: 3 },
    ideal: 'Ascension',
    bond: 'Loyal to the Nemesis Signal',
    flaw: 'Zealous',
    flawDc: 14,
    tier: 4,
    archetype: 'veteran',
  },
  {
    id: 'npc-the-broker',
    name: 'The Broker',
    shipName: 'Information Age',
    stats: { PILOT: 1, GUNS: 0, TRADE: 5, GRIT: 1, GUILE: 5 },
    ideal: 'Knowledge',
    bond: "Owns everyone's secrets",
    flaw: 'Manipulative',
    flawDc: 12,
    tier: 4,
    archetype: 'trader',
  },
  {
    id: 'npc-rust-bucket',
    name: 'Rust Bucket',
    shipName: 'Junk Heap',
    stats: { PILOT: 2, GUNS: 1, TRADE: 3, GRIT: 4, GUILE: 1 },
    ideal: 'Utility',
    bond: 'Protects their stash',
    flaw: 'Hoarder',
    flawDc: 13,
    tier: 1,
    archetype: 'trader',
  },
];

export const ALL_NPC_PROFILES: NpcProfile[] = [...NPC_PROFILES, ...QUEST_PROFILES];

/**
 * THE ONE PREDICATE for "does this record take a turn in the daily simulation?"
 *
 * `state.npcs` carries **41** records — the 30 in {@link NPC_PROFILES} who are
 * fully simulated and mortal, plus the 11 in {@link QUEST_PROFILES} who are set
 * aside for STORYLINE ONLY (owner, 2026-07-29) and take no turn. They hold
 * `NpcState` records so storylet triggers and dispositions can look them up by
 * id, and they sit FROZEN at their day-1 credits, ship and system for an entire
 * career. That is the design, not an oversight: the split replaced an earlier
 * "eleven immortal captains" idea, which was dropped because a cast where a
 * third of the names cannot die made no thematic sense. Reading the eleven as
 * simulated captains is the mistake this predicate exists to prevent.
 *
 * That distinction has now caused FOUR live bugs by being spelled a different
 * way at each call site (or not at all): the Honor List silently became a 42-way
 * board ranking eleven day-1 captains; `balance-rig.test.ts` lost 52 tests to a
 * hardcoded 30; `campaign.test.ts`'s NPC wealth-spread invariant took its MEDIAN
 * over all 41, so eleven records pinned at 5,000cr set the median and the
 * assertion read a 344x spread where the simulated field's was 10.3x; and
 * `sampleMilestone` sampled all 41, quietly diluting **every NPC wealth, hull
 * and position percentile this project has measured** since the roster split.
 *
 * So it is one exported predicate over a Set, not a `.some()` at each site:
 * three numbers stay distinct (`NPC_PROFILES.length` = the simulated field,
 * `state.npcs.length` = the record count, 31 = the Honor List board), and the
 * next reader gets the right one by asking rather than by remembering. Note the
 * polarity: it asks whether a record IS simulated rather than whether it is a
 * quest character, so a record with an unrecognised profile is excluded rather
 * than fed to a turn resolver that would throw on it.
 */
const SIMULATED_PROFILE_IDS: ReadonlySet<string> = new Set(NPC_PROFILES.map((p) => p.id));

export function isSimulatedCaptain(profileId: string): boolean {
  return SIMULATED_PROFILE_IDS.has(profileId);
}

export const ANONYMOUS_INTERCEPTORS: AnonymousInterceptorProfile[] = [
  {
    id: 'anon-pirate-1',
    kind: 'PIRATE',
    rosterIndex: 1,
    name: 'K)(akj',
    shipName: 'K1++++',
    shipClass: 'Maligna Bat',
    homeSystem: 'Pollux-7',
    stats: { PILOT: 1, GUNS: 0, TRADE: 0, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-pirate-2',
    kind: 'PIRATE',
    rosterIndex: 2,
    name: 'K)(ych',
    shipName: 'K2@@@@',
    shipClass: 'Maligna Cat',
    homeSystem: 'Denebola-5',
    stats: { PILOT: 0, GUNS: 0, TRADE: 0, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-pirate-3',
    kind: 'PIRATE',
    rosterIndex: 3,
    name: 'K)(sfy',
    shipName: 'K3####',
    shipClass: 'Maligna Rat',
    homeSystem: 'Denebola-5',
    stats: { PILOT: 0, GUNS: 0, TRADE: 1, GRIT: 1, GUILE: 1 },
    tier: 2,
  },
  {
    id: 'anon-pirate-4',
    kind: 'PIRATE',
    rosterIndex: 4,
    name: 'K)(sdf',
    shipName: 'K4$$$$',
    shipClass: 'Maligna Tat',
    homeSystem: 'Aldebaran-1',
    stats: { PILOT: 0, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 2,
  },
  {
    id: 'anon-pirate-5',
    kind: 'PIRATE',
    rosterIndex: 5,
    name: 'K)(ssf',
    shipName: 'K5%%%%',
    shipClass: 'Maligna Vat',
    homeSystem: 'Altair-3',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 3,
  },
  {
    id: 'anon-pirate-6',
    kind: 'PIRATE',
    rosterIndex: 6,
    name: 'K)(dfy',
    shipName: 'K6^^^^',
    shipClass: 'Maligna Wat',
    homeSystem: 'Altair-3',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 2 },
    tier: 3,
  },
  {
    id: 'anon-pirate-7',
    kind: 'PIRATE',
    rosterIndex: 7,
    name: 'K)(dsh',
    shipName: 'K7&&&&',
    shipClass: 'Maligna Xat',
    homeSystem: 'Pollux-7',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 2 },
    tier: 4,
  },
  {
    id: 'anon-pirate-8',
    kind: 'PIRATE',
    rosterIndex: 8,
    name: 'K)(ech',
    shipName: 'K8****',
    shipClass: 'Maligna Yat',
    homeSystem: 'Aldebaran-1',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 2 },
    tier: 4,
  },
  {
    id: 'anon-pirate-9',
    kind: 'PIRATE',
    rosterIndex: 9,
    name: 'K)(chy',
    shipName: 'K9((((',
    shipClass: 'Maligna Zat',
    homeSystem: 'Denebola-5',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 2 },
    tier: 5,
  },
  {
    id: 'anon-patrol-1',
    kind: 'PATROL',
    rosterIndex: 1,
    name: 'Lt.Savage',
    shipName: 'SP1.Thor',
    shipClass: 'SLOOP',
    homeSystem: 'Procyon-5',
    stats: { PILOT: 1, GUNS: 0, TRADE: 1, GRIT: 0, GUILE: 0 },
    tier: 1,
  },
  {
    id: 'anon-patrol-2',
    kind: 'PATROL',
    rosterIndex: 2,
    name: 'Cmdr.Strong',
    shipName: 'SP2.Hercules',
    shipClass: 'CUTTER',
    homeSystem: 'Mira-9',
    stats: { PILOT: 0, GUNS: 0, TRADE: 1, GRIT: 0, GUILE: 0 },
    tier: 1,
  },
  {
    id: 'anon-patrol-3',
    kind: 'PATROL',
    rosterIndex: 3,
    name: 'Como.Brainerd',
    shipName: 'SP3.Fearless',
    shipClass: 'BARK',
    homeSystem: 'Fomalhaut-2',
    stats: { PILOT: 0, GUNS: 1, TRADE: 1, GRIT: 0, GUILE: 0 },
    tier: 2,
  },
  {
    id: 'anon-patrol-4',
    kind: 'PATROL',
    rosterIndex: 4,
    name: 'Capt.Brutus',
    shipName: 'SP4.Darkover',
    shipClass: 'BRIGANTINE',
    homeSystem: 'Procyon-5',
    stats: { PILOT: 0, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 2,
  },
  {
    id: 'anon-patrol-5',
    kind: 'PATROL',
    rosterIndex: 5,
    name: 'Capt.Armand',
    shipName: 'SP5.Courageous',
    shipClass: 'CORVETTE',
    homeSystem: 'Regulus-6',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 3,
  },
  {
    id: 'anon-patrol-6',
    kind: 'PATROL',
    rosterIndex: 6,
    name: 'Capt.Bouchet',
    shipName: 'SP6.Firedrake',
    shipClass: 'DESTROYER',
    homeSystem: 'Pollux-7',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 3,
  },
  {
    id: 'anon-patrol-7',
    kind: 'PATROL',
    rosterIndex: 7,
    name: 'Capt.Brax',
    shipName: 'SP7.Victorious',
    shipClass: 'CRUISER',
    homeSystem: 'Procyon-5',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 4,
  },
  {
    id: 'anon-patrol-8',
    kind: 'PATROL',
    rosterIndex: 8,
    name: 'Adm.Wong',
    shipName: 'SP8.Meritorious',
    shipClass: 'FRIGATE',
    homeSystem: 'Deneb-4',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 4,
  },
  {
    id: 'anon-patrol-9',
    kind: 'PATROL',
    rosterIndex: 9,
    name: 'Adm.Hutchins',
    shipName: 'SP9.Incredible',
    shipClass: 'BATTLESHIP',
    homeSystem: 'Aldebaran-1',
    stats: { PILOT: 1, GUNS: 2, TRADE: 1, GRIT: 1, GUILE: 0 },
    tier: 4,
  },
  {
    id: 'anon-patrol-10',
    kind: 'PATROL',
    rosterIndex: 10,
    name: 'Adm.Bruiser',
    shipName: 'SPX.Inferno',
    shipClass: 'DEATHSTAR',
    homeSystem: 'Arcturus-6',
    stats: { PILOT: 2, GUNS: 2, TRADE: 1, GRIT: 2, GUILE: 0 },
    tier: 5,
  },
  {
    id: 'anon-patrol-11',
    kind: 'PATROL',
    rosterIndex: 11,
    name: 'Adm.Borgia',
    shipName: 'SPZ.Infinity',
    shipClass: 'INFINITY',
    homeSystem: 'Altair-3',
    stats: { PILOT: 2, GUNS: 3, TRADE: 1, GRIT: 3, GUILE: 0 },
    tier: 5,
  },
  {
    id: 'anon-rim-pirate-1',
    kind: 'RIM_PIRATE',
    rosterIndex: 1,
    name: 'RP-Black Bart',
    shipName: 'Gypsy Lee',
    shipClass: 'Sailfish',
    homeSystem: 'Antares-5',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-rim-pirate-2',
    kind: 'RIM_PIRATE',
    rosterIndex: 2,
    name: 'RP-Blackbeard',
    shipName: 'Buccaneer',
    shipClass: 'Swordfish',
    homeSystem: 'Capella-4',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-rim-pirate-3',
    kind: 'RIM_PIRATE',
    rosterIndex: 3,
    name: 'RP-Anne Bonny',
    shipName: 'Red Witch',
    shipClass: 'Barracuda',
    homeSystem: 'Polaris-1',
    stats: { PILOT: 1, GUNS: 1, TRADE: 1, GRIT: 1, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-rim-pirate-4',
    kind: 'RIM_PIRATE',
    rosterIndex: 4,
    name: 'RP-Mary Read',
    shipName: 'Sea Witch',
    shipClass: 'Hammerhead',
    homeSystem: 'Mizar-9',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-rim-pirate-5',
    kind: 'RIM_PIRATE',
    rosterIndex: 5,
    name: 'RP-Long Ben',
    shipName: 'Marauder',
    shipClass: 'Moray',
    homeSystem: 'Achernar-5',
    stats: { PILOT: 1, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 1 },
    tier: 2,
  },
  {
    id: 'anon-rim-pirate-6',
    kind: 'RIM_PIRATE',
    rosterIndex: 6,
    name: 'RP-Henry Morgan',
    shipName: 'Rascal',
    shipClass: 'Moray',
    homeSystem: 'Algol-2',
    stats: { PILOT: 2, GUNS: 2, TRADE: 1, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-rim-pirate-7',
    kind: 'RIM_PIRATE',
    rosterIndex: 7,
    name: 'RP-Piet Nym',
    shipName: 'Golden Fleece',
    shipClass: 'Mako',
    homeSystem: 'Antares-5',
    stats: { PILOT: 2, GUNS: 2, TRADE: 0, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-rim-pirate-8',
    kind: 'RIM_PIRATE',
    rosterIndex: 8,
    name: 'RP-Long J.Silver',
    shipName: 'Golden Hiney',
    shipClass: 'Thresher',
    homeSystem: 'Capella-4',
    stats: { PILOT: 2, GUNS: 2, TRADE: 0, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-rim-pirate-9',
    kind: 'RIM_PIRATE',
    rosterIndex: 9,
    name: 'RP-Peg-Leg Smith',
    shipName: 'She Devil',
    shipClass: 'Marlin',
    homeSystem: 'Polaris-1',
    stats: { PILOT: 2, GUNS: 2, TRADE: 1, GRIT: 2, GUILE: 2 },
    tier: 3,
  },
  {
    id: 'anon-rim-pirate-10',
    kind: 'RIM_PIRATE',
    rosterIndex: 10,
    name: "RP-Cap'n Jack",
    shipName: 'Fancy Dancy',
    shipClass: 'Orca',
    homeSystem: 'Mizar-9',
    stats: { PILOT: 3, GUNS: 3, TRADE: 0, GRIT: 3, GUILE: 2 },
    tier: 3,
  },
  {
    id: 'anon-rim-pirate-11',
    kind: 'RIM_PIRATE',
    rosterIndex: 11,
    name: 'RP-Lord Tim',
    shipName: 'Fauntleroy',
    shipClass: 'Manta',
    homeSystem: 'Achernar-5',
    stats: { PILOT: 3, GUNS: 3, TRADE: 0, GRIT: 3, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-rim-pirate-12',
    kind: 'RIM_PIRATE',
    rosterIndex: 12,
    name: "RP-Cap'n Ahab",
    shipName: 'Moby Dick',
    shipClass: 'Giant Squid',
    homeSystem: 'Algol-2',
    stats: { PILOT: 3, GUNS: 3, TRADE: 1, GRIT: 3, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-rim-pirate-13',
    kind: 'RIM_PIRATE',
    rosterIndex: 13,
    name: 'RP-Dirty Jack',
    shipName: 'Brass Tack',
    shipClass: 'Halibut',
    homeSystem: 'Antares-5',
    stats: { PILOT: 3, GUNS: 3, TRADE: 0, GRIT: 3, GUILE: 3 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-14',
    kind: 'RIM_PIRATE',
    rosterIndex: 14,
    name: 'RP-Good John',
    shipName: 'Coppersides',
    shipClass: 'Flounder',
    homeSystem: 'Capella-4',
    stats: { PILOT: 4, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 3 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-15',
    kind: 'RIM_PIRATE',
    rosterIndex: 15,
    name: 'RP-Messy Frank',
    shipName: 'Silversides',
    shipClass: 'Sea Bass',
    homeSystem: 'Polaris-1',
    stats: { PILOT: 4, GUNS: 4, TRADE: 1, GRIT: 4, GUILE: 3 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-16',
    kind: 'RIM_PIRATE',
    rosterIndex: 16,
    name: 'RP-Farragut',
    shipName: 'Lady Luck',
    shipClass: 'Lionfish',
    homeSystem: 'Mizar-9',
    stats: { PILOT: 4, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-17',
    kind: 'RIM_PIRATE',
    rosterIndex: 17,
    name: 'RP-Van Mere',
    shipName: "Witch's Brew",
    shipClass: 'Tetrapod',
    homeSystem: 'Achernar-5',
    stats: { PILOT: 4, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-rim-pirate-18',
    kind: 'RIM_PIRATE',
    rosterIndex: 18,
    name: 'RP-Van Slab',
    shipName: "Devil's Spout",
    shipClass: 'Gastropod',
    homeSystem: 'Algol-2',
    stats: { PILOT: 5, GUNS: 5, TRADE: 1, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
  {
    id: 'anon-rim-pirate-19',
    kind: 'RIM_PIRATE',
    rosterIndex: 19,
    name: 'RP-Innkeeper',
    shipName: 'Purple Smaze',
    shipClass: 'Euchuroidea',
    homeSystem: 'Antares-5',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
  {
    id: 'anon-rim-pirate-20',
    kind: 'RIM_PIRATE',
    rosterIndex: 20,
    name: 'RP-Polly Nyces',
    shipName: 'Moon Snail',
    shipClass: 'Starfish',
    homeSystem: 'Capella-4',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
  {
    id: 'anon-rim-pirate-21',
    kind: 'RIM_PIRATE',
    rosterIndex: 21,
    name: 'RP-Alienator',
    shipName: 'PREDATOR',
    shipClass: 'Symbiote',
    homeSystem: 'Algol-2',
    stats: { PILOT: 5, GUNS: 5, TRADE: 1, GRIT: 5, GUILE: 5 },
    tier: 5,
  },
  {
    id: 'anon-brigand-1',
    kind: 'BRIGAND',
    rosterIndex: 1,
    name: 'Cruncher',
    shipName: 'Big Mac',
    shipClass: 'N1.Sloop',
    homeSystem: 'Sun-3',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-brigand-2',
    kind: 'BRIGAND',
    rosterIndex: 2,
    name: 'Chomper',
    shipName: 'Nugget',
    shipClass: 'N1.Sloop',
    homeSystem: 'Aldebaran-1',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-brigand-3',
    kind: 'BRIGAND',
    rosterIndex: 3,
    name: 'Stomper',
    shipName: 'Fish Stix',
    shipClass: 'N1.Sloop',
    homeSystem: 'Altair-3',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 1 },
    tier: 1,
  },
  {
    id: 'anon-brigand-4',
    kind: 'BRIGAND',
    rosterIndex: 4,
    name: 'Bruiser',
    shipName: 'Fries',
    shipClass: 'N1.Sloop',
    homeSystem: 'Arcturus-6',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-brigand-5',
    kind: 'BRIGAND',
    rosterIndex: 5,
    name: 'Bonker',
    shipName: 'Pop Tart',
    shipClass: 'N1.Sloop',
    homeSystem: 'Deneb-4',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-brigand-6',
    kind: 'BRIGAND',
    rosterIndex: 6,
    name: 'Blaster',
    shipName: 'Twinkie',
    shipClass: 'N1.Sloop',
    homeSystem: 'Denebola-5',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-brigand-7',
    kind: 'BRIGAND',
    rosterIndex: 7,
    name: 'Bumper',
    shipName: 'Ho-Ho',
    shipClass: 'N1.Sloop',
    homeSystem: 'Fomalhaut-2',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-brigand-8',
    kind: 'BRIGAND',
    rosterIndex: 8,
    name: 'Buster',
    shipName: 'Jelly Bean',
    shipClass: 'N1.Sloop',
    homeSystem: 'Mira-9',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-brigand-9',
    kind: 'BRIGAND',
    rosterIndex: 9,
    name: 'Booster',
    shipName: 'Jube-Jube',
    shipClass: 'N1.Sloop',
    homeSystem: 'Pollux-7',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-brigand-10',
    kind: 'BRIGAND',
    rosterIndex: 10,
    name: 'Bugster',
    shipName: 'Taco',
    shipClass: 'N1.Sloop',
    homeSystem: 'Procyon-5',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-brigand-11',
    kind: 'BRIGAND',
    rosterIndex: 11,
    name: 'Bammer',
    shipName: 'Chips',
    shipClass: 'N1.Sloop',
    homeSystem: 'Regulus-6',
    stats: { PILOT: 0, GUNS: 0, TRADE: 2, GRIT: 0, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-brigand-12',
    kind: 'BRIGAND',
    rosterIndex: 12,
    name: 'Bummer',
    shipName: 'McDLT',
    shipClass: 'N1.Sloop',
    homeSystem: 'Rigel-8',
    stats: { PILOT: 1, GUNS: 1, TRADE: 2, GRIT: 1, GUILE: 5 },
    tier: 5,
  },
  {
    id: 'anon-reptiloid-1',
    kind: 'REPTILOID',
    rosterIndex: 1,
    name: 'Admiral Assss',
    shipName: 'SS Anaconda',
    shipClass: 'S1-Snake',
    homeSystem: 'NGC-44',
    stats: { PILOT: 5, GUNS: 0, TRADE: 0, GRIT: 1, GUILE: 2 },
    tier: 1,
  },
  {
    id: 'anon-reptiloid-2',
    kind: 'REPTILOID',
    rosterIndex: 2,
    name: 'Admiral Bssss',
    shipName: 'SS Bull',
    shipClass: 'S2-Snake',
    homeSystem: 'NGC-55',
    stats: { PILOT: 5, GUNS: 1, TRADE: 0, GRIT: 1, GUILE: 2 },
    tier: 1,
  },
  {
    id: 'anon-reptiloid-3',
    kind: 'REPTILOID',
    rosterIndex: 3,
    name: 'Admiral Cssss',
    shipName: 'SS Copperhead',
    shipClass: 'S3-Snake',
    homeSystem: 'NGC-66',
    stats: { PILOT: 5, GUNS: 1, TRADE: 0, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-reptiloid-4',
    kind: 'REPTILOID',
    rosterIndex: 4,
    name: 'Admiral Dssss',
    shipName: 'SS Fer-de-Lance',
    shipClass: 'S4-Snake',
    homeSystem: 'NGC-77',
    stats: { PILOT: 4, GUNS: 2, TRADE: 0, GRIT: 2, GUILE: 2 },
    tier: 2,
  },
  {
    id: 'anon-reptiloid-5',
    kind: 'REPTILOID',
    rosterIndex: 5,
    name: 'Admiral Essss',
    shipName: 'SS Garter',
    shipClass: 'S5-Snake',
    homeSystem: 'NGC-88',
    stats: { PILOT: 4, GUNS: 2, TRADE: 0, GRIT: 3, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-reptiloid-6',
    kind: 'REPTILOID',
    rosterIndex: 6,
    name: 'Admiral Fssss',
    shipName: 'SS Indigo',
    shipClass: 'S6-Snake',
    homeSystem: 'NGC-99',
    stats: { PILOT: 4, GUNS: 3, TRADE: 0, GRIT: 3, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-reptiloid-7',
    kind: 'REPTILOID',
    rosterIndex: 7,
    name: 'Admiral Gssss',
    shipName: 'SS Viper',
    shipClass: 'S7-Snake',
    homeSystem: 'NGC-44',
    stats: { PILOT: 4, GUNS: 3, TRADE: 0, GRIT: 4, GUILE: 3 },
    tier: 3,
  },
  {
    id: 'anon-reptiloid-8',
    kind: 'REPTILOID',
    rosterIndex: 8,
    name: 'Admiral Hssss',
    shipName: 'SS Coral',
    shipClass: 'S8-Snake',
    homeSystem: 'NGC-55',
    stats: { PILOT: 5, GUNS: 4, TRADE: 0, GRIT: 4, GUILE: 3 },
    tier: 4,
  },
  {
    id: 'anon-reptiloid-9',
    kind: 'REPTILOID',
    rosterIndex: 9,
    name: 'Admiral Issss',
    shipName: 'SS Rattler',
    shipClass: 'S9-Snake',
    homeSystem: 'NGC-66',
    stats: { PILOT: 5, GUNS: 4, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-reptiloid-10',
    kind: 'REPTILOID',
    rosterIndex: 10,
    name: 'Admiral Kssss',
    shipName: 'SS Asp',
    shipClass: 'SX-Snake',
    homeSystem: 'NGC-77',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 4,
  },
  {
    id: 'anon-reptiloid-11',
    kind: 'REPTILOID',
    rosterIndex: 11,
    name: 'Admiral Lssss',
    shipName: 'SS Adder',
    shipClass: 'SY-Snake',
    homeSystem: 'NGC-88',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
  {
    id: 'anon-reptiloid-12',
    kind: 'REPTILOID',
    rosterIndex: 12,
    name: 'Admiral Mssss',
    shipName: 'SS Cobra',
    shipClass: 'SZ-Snake',
    homeSystem: 'NGC-99',
    stats: { PILOT: 5, GUNS: 5, TRADE: 0, GRIT: 5, GUILE: 4 },
    tier: 5,
  },
];
